name: Artifact

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    strategy:
      matrix:
        edition: [oss, ee]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Artifact zip URL
        run: |
          get_parent () {
            parent_commit=$(git rev-parse $1^)
            echo $parent_commit
          }

          main () {
            parent_commit=$(get_parent $1)
            echo $parent_commit

            current_page=${2:-1}

            artifacts=$(curl -sL \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/metabase/metabase/actions/artifacts?name=metabase-${{ matrix.edition }}-uberjar&per_page=100&page=$current_page")


            zip=$(echo $artifacts | jq '[.artifacts[] | {url: .url, dl: .archive_download_url, run: .workflow_run}]' \
            | jq -c --arg COMMIT "$parent_commit" '[.[] | select(.run.head_sha | contains($COMMIT))'.dl] | jq '.[0] | select (.!=null)')

            if [[ $zip ]]; then
                echo $zip
            elif [[ $current_page -le 5 ]]; then
                echo "Didn't find the artifact for '$parent_commit' on the page: $current_page."
                current_page=$((++current_page))
                main $parent_commit $current_page
            else
              echo "Switching to a new parent"
              parent_commit=$(get_parent parent_commit)
              exit 1
              # main $(get_parent $parent_commit)
            fi
          }

          main "HEAD"
        id: foobar
        shell: bash
