name: Codespell

on:
  push:
    branches:
      - 'master'
      - 'release-**'
  pull_request:

jobs:

  codespell:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: codespell-project/actions-codespell@v1
        with:
          ignore_words_file: .codespellignore
